# Generated by Django 3.2.3 on 2021-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0002_auto_20210515_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_to_fly',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
